version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10.9.0-stretch-browsers
     steps:
       - checkout
       - restore_cache:
           key: npm-deps-{{ checksum "package.json" }}
       - run: npm i
       - save_cache:
           key: npm-deps-{{ checksum "package.json" }}
           paths:
             - node_modules
       - run: npm run lint
       - run: npm test
